# _linked_dict.pyi
# Static type hints for the compiled `_linked_dict` Cython extension.

from collections.abc import Iterator, KeysView
from typing import Generic, TypeVar

K = TypeVar('K')
V = TypeVar('V')

class LinkedDict(Generic[K, V]):
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def get(self, key: K, default: V | None = ...) -> V | None: ...
    def pop(self, key: K) -> V: ...
    def move_to_tail(self, key: K) -> None: ...
    def keys(self) -> KeysView[K]: ...
    def values(self) -> Iterator[V]: ...
    def items(self) -> Iterator[tuple[K, V]]: ...
    def mutable_values(self) -> Iterator[V]: ...
