#!/usr/bin/env python
#
#    Copyright (C) 2008  Nikolaus Rath <Nikolaus@rath.org>
#
#    This program can be distributed under the terms of the GNU LGPL.
#


# Python boto uses several deprecated modules
import warnings
warnings.filterwarnings("ignore", "", DeprecationWarning, "boto")


import unittest
import os
import sys

# Runs all tests in test/ directory
def suite():
    modules_to_test =  [ "tests." + name[:-3] for name in
                         os.listdir(os.path.join(os.path.dirname(__file__), "tests"))
                         if name.endswith(".py") and not name.startswith("__") ]
    map(__import__, modules_to_test)
    alltests = unittest.TestSuite()
    for name in modules_to_test:
        alltests.addTest(unittest.findTestCases(sys.modules[name]))
    return alltests

if __name__ == '__main__':
    unittest.main(defaultTest='suite')
