#!/usr/bin/env python
#
#    Copyright (C) 2008  Nikolaus Rath <Nikolaus@rath.org>
#
#    This program can be distributed under the terms of the GNU LGPL.
#


# Python boto uses several deprecated modules
import warnings
warnings.filterwarnings("ignore", "", DeprecationWarning, "boto")

import unittest
import os
import sys

# Find and import tests
testdir = os.path.join(os.path.dirname(__file__), "tests")
sys.path.insert(0,testdir)
modules_to_test =  [ name[:-3] for name in os.listdir(testdir) if name.endswith(".py") ]

# Import the modules
# We need to add them to the global namespace in order for
# unittest.main() to find them if specific tests are given on
# the command line.
for name in modules_to_test:
    globals()[name] = __import__(name)


# Runs all tests in test/ directory
def suite():
    alltests = unittest.TestSuite()
    for name in modules_to_test:
        alltests.addTest(unittest.findTestCases(sys.modules[name]))
    return alltests
    
unittest.main(defaultTest='suite')
