#!/usr/bin/env python3
"""Automate the mechanical steps of an S3QL release.

Reads the new version from the topmost heading in ChangeLog.rst, then in
order: optionally rotates signify keys for a new minor/major release, bumps
version strings in source files, refreshes AUTHORS, commits and tags the
release, builds docs and sdist, signs the tarball, rsyncs the docs, and
prints the announcement email with the remaining manual steps.
"""

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHANGELOG = ROOT / 'ChangeLog.rst'
SIGNIFY_DIR = ROOT / 'signify'
INIT_PY = ROOT / 'src' / 's3ql' / '__init__.py'
PYPROJECT = ROOT / 'pyproject.toml'
AUTHORS_FILE = ROOT / 'AUTHORS'
RSYNC_TARGET = 'ebox.rath.org:/srv/www.rath.org/s3ql-docs/'

VERSION_HEADING_RE = re.compile(r'^S3QL\s+(\d+\.\d+\.\d+)\s+\(\d{4}-\d{2}-\d{2}\)\s*$')

# Hardcoded verbatim from AUTHORS; must stay in sync if ever the header changes.
AUTHORS_PREAMBLE = """\
Current Maintainer
------------------

Nikolaus Rath <Nikolaus@rath.org>

Contributors
------------

The following people have contributed patches to S3QL (autogenerated
list):

"""

ANNOUNCEMENT_TEMPLATE = """\
From: Nikolaus Rath <Nikolaus@rath.org>
Subject: [s3ql] [ANNOUNCE] S3QL {new_ver} has been released
To: s3ql@googlegroups.com

Dear all,

I am pleased to announce a new release of S3QL, version {new_ver}.

From the changelog:
{changelog}

The following people have contributed code to this release:

{contributors}

(The full list of contributors is available in the AUTHORS file).

The release is available for download from
https://github.com/s3ql/s3ql/releases

Please report any bugs on the mailing list (s3ql@googlegroups.com) or
the issue tracker (https://github.com/s3ql/s3ql/issues).

Best,
-Nikolaus
"""

_BOT_RE = re.compile(r'copilot|claude|\[bot\]|<none@none>', re.IGNORECASE)


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    """Run *cmd*, echoing it first. Raises on non-zero exit."""
    print('+', ' '.join(cmd), flush=True)
    return subprocess.run(cmd, check=True, text=True)


def capture(cmd: list[str]) -> str:
    """Run *cmd* and return its stdout. Raises on non-zero exit."""
    print('+', ' '.join(cmd), flush=True)
    return subprocess.run(cmd, check=True, text=True, capture_output=True).stdout


def check_tools() -> None:
    missing = [t for t in ('jj', 'signify', 'uv', 'rsync') if shutil.which(t) is None]
    if missing:
        sys.exit(f"error: required tools not found in $PATH: {', '.join(missing)}")


def signing_keys_dir() -> Path:
    val = os.environ.get('S3QL_SIGNING_KEYS_DIR')
    if not val:
        sys.exit('error: $S3QL_SIGNING_KEYS_DIR is not set.')
    p = Path(val)
    if not p.is_dir():
        sys.exit(f'error: $S3QL_SIGNING_KEYS_DIR={val!r} is not a directory.')
    return p


def parse_changelog() -> tuple[str, str]:
    """Return *(new_ver, changelog_body)* from the topmost heading in ChangeLog.rst."""
    lines = CHANGELOG.read_text().splitlines()
    new_ver: str | None = None
    body_start: int | None = None
    body_end: int = len(lines)
    for i, line in enumerate(lines):
        if i + 1 >= len(lines):
            continue
        underline = lines[i + 1]
        if not underline or set(underline) - {'='} or len(underline) < len(line):
            continue
        m = VERSION_HEADING_RE.match(line)
        if not m:
            continue
        if new_ver is None:
            new_ver = m.group(1)
            body_start = i + 2
        else:
            body_end = i
            break
    if new_ver is None or body_start is None:
        sys.exit(
            "error: no 'S3QL X.Y.Z (YYYY-MM-DD)' heading found in ChangeLog.rst — "
            'add a release heading before running this script.'
        )
    body = '\n'.join(lines[body_start:body_end]).strip()
    return new_ver, body


def find_prev_tag() -> str:
    """Return the most recent s3ql-X.Y.Z tag from `jj tag list`."""
    raw = capture(['jj', 'tag', 'list'])
    tags = [
        m.group(1) for line in raw.splitlines() if (m := re.match(r'^(s3ql-\d+\.\d+\.\d+):', line))
    ]
    if not tags:
        sys.exit('error: no s3ql-* tags found — is this the right repository?')
    tags.sort(key=lambda t: tuple(int(x) for x in t.removeprefix('s3ql-').split('.')))
    return tags[-1]


def rotate_keys(major_rev: str, keys_dir: Path) -> None:
    """Rotate signify keys for a new major revision.

    Renames next.{pub,sec} to {major_rev}.{pub,sec} and generates a fresh
    next pair for future use. Assumes *keys_dir* holds the secret key
    `s3ql-next.sec` and that `signify/s3ql-next.pub` is the matching public key.
    """
    print(f'Rotating signify keys for new major revision {major_rev}.')
    next_pub = SIGNIFY_DIR / 's3ql-next.pub'
    next_sec = keys_dir / 's3ql-next.sec'
    new_pub = SIGNIFY_DIR / f's3ql-{major_rev}.pub'
    new_sec = keys_dir / f's3ql-{major_rev}.sec'

    for path, label in [
        (next_pub, 'signify/s3ql-next.pub'),
        (next_sec, '$S3QL_SIGNING_KEYS_DIR/s3ql-next.sec'),
    ]:
        if not path.exists():
            sys.exit(f'error: expected {label} to exist for key rotation.')
    if new_sec.exists():
        sys.exit(
            f'error: {new_sec} already exists — has key rotation already been done for {major_rev}?'
        )

    next_pub.rename(new_pub)
    print(f'Renamed s3ql-next.pub → s3ql-{major_rev}.pub')
    next_sec.rename(new_sec)
    print(f'Renamed s3ql-next.sec → s3ql-{major_rev}.sec')

    run(['signify', '-G', '-n', '-p', str(next_pub), '-s', str(next_sec)])


def bump_version(new_ver: str) -> None:
    """Update VERSION in __init__.py and version in pyproject.toml."""
    init_text = INIT_PY.read_text()
    init_updated = re.sub(
        r"^VERSION = '.*'$", f"VERSION = '{new_ver}'", init_text, flags=re.MULTILINE
    )
    if init_updated == init_text:
        sys.exit(f'error: VERSION = ... not found in {INIT_PY}')
    INIT_PY.write_text(init_updated)
    print(f'Updated {INIT_PY.relative_to(ROOT)} → {new_ver}')

    pyproject_text = PYPROJECT.read_text()
    pyproject_updated = re.sub(
        r'^version = ".*"$', f'version = "{new_ver}"', pyproject_text, count=1, flags=re.MULTILINE
    )
    if pyproject_updated == pyproject_text:
        sys.exit(f'error: version = ... not found in {PYPROJECT}')
    PYPROJECT.write_text(pyproject_updated)
    print(f'Updated {PYPROJECT.relative_to(ROOT)} → {new_ver}')


def _skip_author(line: str) -> bool:
    stripped = line.strip()
    return not stripped or stripped.endswith('<>') or bool(_BOT_RE.search(stripped))


def refresh_authors() -> None:
    """Regenerate AUTHORS from the full jj commit history."""
    raw = capture(
        [
            'jj',
            'log',
            '--no-graph',
            '-r',
            'all()',
            '--template',
            'author.name() ++ " <" ++ author.email() ++ "\\n"',
        ]
    )
    contributors = sorted(
        {ln.strip() for ln in raw.splitlines() if not _skip_author(ln)},
        key=str.casefold,
    )
    AUTHORS_FILE.write_text(AUTHORS_PREAMBLE + '\n'.join(contributors) + '\n')
    print(f'Refreshed AUTHORS ({len(contributors)} contributors).')


def get_release_contributors(prev_tag: str) -> str:
    """Return a sorted contributor list for commits since *prev_tag*."""
    raw = capture(
        [
            'jj',
            'log',
            '--no-graph',
            '-r',
            f'{prev_tag}..@',
            '--template',
            'author.name() ++ " <" ++ author.email() ++ "\\n"',
        ]
    )
    seen = sorted(
        {ln.strip() for ln in raw.splitlines() if not _skip_author(ln)},
        key=str.casefold,
    )
    return '\n'.join(seen) if seen else '(none)'


def build_docs() -> None:
    doc_args = ['-W', '--keep-going', '-d', 'doc/doctrees']
    run(['uv', 'run', 'sphinx-build', *doc_args, '-b', 'html', 'rst/', 'doc/html/'])
    run(['uv', 'run', 'sphinx-build', *doc_args, '-b', 'man', 'rst/', 'doc/manpages/'])
    for name in ('expire_backups.1', 'pcp.1'):
        src = ROOT / 'doc' / 'manpages' / name
        if src.exists():
            dst = ROOT / 'contrib' / name
            src.rename(dst)
            print(f'Moved {src.name} → contrib/')


def build_and_sign(new_ver: str, major_rev: str, keys_dir: Path) -> None:
    run(['uv', 'sync', '--locked'])
    build_docs()
    run(['uv', 'build', '--sdist'])

    tarball = ROOT / 'dist' / f's3ql-{new_ver}.tar.gz'
    if not tarball.exists():
        sys.exit(f'error: expected {tarball} after `uv build --sdist`.')

    run(['signify', '-S', '-s', str(keys_dir / f's3ql-{major_rev}.sec'), '-m', str(tarball)])


def main() -> None:
    os.chdir(ROOT)
    check_tools()

    keys_dir = signing_keys_dir()

    new_ver, changelog = parse_changelog()
    major_rev = new_ver.rsplit('.', 1)[0]
    new_tag = f's3ql-{new_ver}'
    print(f'Releasing S3QL {new_ver} (major revision {major_rev}).')

    prev_tag = find_prev_tag()
    prev_ver = prev_tag.removeprefix('s3ql-')
    prev_major_rev = prev_ver.rsplit('.', 1)[0]

    if major_rev != prev_major_rev:
        rotate_keys(major_rev, keys_dir)
    else:
        print(f'Bugfix release on {major_rev}; no key rotation needed.')

    bump_version(new_ver)
    run(['uv', 'lock'])
    refresh_authors()

    run(['jj', 'describe', '-m', f'Released {new_tag}'])
    run(['jj', 'tag', 'set', new_tag, '-r', '@'])
    run(['jj', 'bookmark', 'move', 'main', '--to=@'])

    build_and_sign(new_ver, major_rev, keys_dir)

    print('Uploading documentation...')
    run(['rsync', '-aHv', '--del', str(ROOT / 'doc' / 'html') + '/', RSYNC_TARGET])

    contributors = get_release_contributors(prev_tag)
    announcement = ANNOUNCEMENT_TEMPLATE.format(
        new_ver=new_ver,
        changelog=changelog,
        contributors=contributors,
    )

    print()
    print(f'Release {new_tag} prepared.')
    print()
    print('--- announcement email ---')
    print(announcement, end='')


if __name__ == '__main__':
    main()
